print("Let's play Silly Sentences!")
name = input("Enter a name: ")
adj1 = input("Enter an adjective: ")
adj2 = input("Enter an adjective: ")
food1 = input("Enter a food: ")
food2 = input("Enter a food: ")
noun = input("Enter a noun: ")
place = input("Enter a place: ")
verb = input("Enter a verb: ")
adverb = input("Enter an adverb: ")
print()
print(name + " was planning a dream vacation to " + place)
print(name + " was especially looking forward to trying the local \n cuisine, including "+ adj1 +","+food1+"and "+ food2+"." )
print()
print(name +" will have to practice the language "+adverb+" to \n make it easier to "+verb+" with people.")
print()
print(name+" has a long list of sights to see, including the\n museum and the "+adj2+" park")